@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}

###

GET http://{{host}}/all HTTP/1.1

###

POST http://{{host}}/entry HTTP/1.1
content-type: application/json
method: 'POST'
body: JSON.stringify(data)
headers: { 'Content-Type': 'application/json', Accept: 'application/json' }

{
  "field": "value",
  "test2": "val2"
}